/*
 *Exercise 15.28:
 *Define a vector to hold Quote objects but put Bulk_quote objects into that vector.
 *Compute the total net_price of all the elements in the vector.
 */

/*
 *Exercise 15.29:
 *Repeat your program, but this time store shared_ptrs to objects of type Quote.
 *Explain any discrepancy in the sum generated by the this version and the previous program.
 *If there is no discrepancy, explain why there isn’t one.
 */

#include <vector>
using std::vector;
#include <iostream>
using std::cout; using std::endl;
#include <memory>
using std::shared_ptr; using std::make_shared;

#include "quote.h"
#include "bulk_quote.h"

int main()
{
    // exercise 15.28
    vector<Quote> qvec;
    qvec.push_back(Bulk_quote("0-201-82470-1", 50.0, 20, 0.1));
    qvec.push_back(Bulk_quote("0-201-82470-1", 51.0, 20, 0.1));
    qvec.push_back(Bulk_quote("0-201-82470-1", 52.0, 20, 0.1));

    double price_sum = 0;
    for (auto b : qvec) {
        price_sum += b.net_price(25);
    }
    cout << price_sum << endl;

    // exercese 15.29
    vector<shared_ptr<Quote>> sqvec;
    sqvec.push_back(make_shared<Bulk_quote>("0-201-82470-1", 50.0, 20, 0.1));
    sqvec.push_back(make_shared<Bulk_quote>("0-201-82470-1", 51.0, 20, 0.1));
    sqvec.push_back(make_shared<Bulk_quote>("0-201-82470-1", 52.0, 20, 0.1));

    double price_sum2 = 0;
    for (auto bp : sqvec) {
        price_sum2 += bp->net_price(25);
    }
    cout << price_sum2 << endl;

    return 0;
}


